//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBasico001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos_Turmas
    {
        public int IDAlunoTurma { get; set; }
        public int IDAlunos { get; set; }
        public int IDTurma { get; set; }
    
        public virtual alunos alunos { get; set; }
        public virtual turmas turmas { get; set; }
    }
}
