//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBasico001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos_Professores
    {
        public int IDFKAlunosProfessores { get; set; }
        public int IDAluno { get; set; }
        public int IDProfessor { get; set; }
    
        public virtual alunos alunos { get; set; }
        public virtual professores professores { get; set; }
    }
}
