//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBasico001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia_Turmas
    {
        public int idMateriaTurma { get; set; }
        public int idTurma { get; set; }
        public int idMateria { get; set; }
    
        public virtual materias materias { get; set; }
        public virtual turmas turmas { get; set; }
    }
}
